"""territorios_pi.py — registry slug→municípios (formato DOM-PI, gerado/validado
contra o formulário ao vivo em 2026-06-04). "do Piauí" aparece abreviado "do Pi".
Teresina/Parnaíba não existem nesta fonte (diário próprio). Use em scraper_isolado."""

TERRITORIOS_MUNICIPIOS = {
    'carnaubais': [
        'Assuncao do Pi',
        'Boa Hora',
        'Boqueirao do Pi',
        'Buriti dos Montes',
        'Cabeceiras do Pi',
        'Campo Maior',
        'Capitao de Campos',
        'Castelo do Pi',
        'Cocal de Telha',
        'Jatoba do Pi',
        'Juazeiro do Pi',
        'Nossa Senhora de Nazare',
        'Novo Santo Antonio',
        'Sao Joao da Serra',
        'Sao Miguel do Tapuio',
        'Sigefredo Pacheco',
    ],
    'cocais': [
        'Barras',
        'Batalha',
        'Brasileira',
        'Campo Largo do Pi',
        'Domingos Mourao',
        'Esperantina',
        'Joaquim Pires',
        'Joca Marques',
        'Lagoa de Sao Francisco',
        'Luzilandia',
        'Madeiro',
        'Matias Olimpio',
        'Milton Brandao',
        'Morro do Chapeu do Pi',
        'Nossa Senhora dos Remedios',
        'Pedro II',
        'Piracuruca',
        'Piripiri',
        'Porto',
        'Sao Joao da Fronteira',
        'Sao Joao do Arraial',
        'Sao Jose do Divino',
    ],
    'vale_do_rio_guaribas': [
        'Alagoinha do Pi',
        'Alegrete do Pi',
        'Aroeiras do Itaim',
        'Bocaina',
        'Campo Grande do Pi',
        'Dom Expedito Lopes',
        'Francisco Santos',
        'Fronteiras',
        'Geminiano',
        'Itainopolis',
        'Monsenhor Hipolito',
        'Paqueta',
        'Picos',
        'Pio IX',
        'Santana do Piaui',
        'Santo Antonio de Lisboa',
        'Sao Joao da Canabrava',
        'Sao Jose do Pi',
        'Sao Juliao',
        'Sao Luis do Pi',
        'Sussuapara',
        'Vera Mendes',
        'Vila Nova do Pi',
    ],
    'chapada_vale_do_rio_itaim': [
        'Acaua',
        'Belem do Pi',
        'Betania do Pi',
        'Caldeirao Grande do Pi',
        'Caridade do Pi',
        'Curral Novo do Pi',
        'Francisco Macedo',
        'Jacobina do Pi',
        'Jaicos',
        'Marcolandia',
        'Massape do Pi',
        'Padre Marcos',
        'Patos do Pi',
        'Paulistana',
        'Queimada Nova',
        'Simoes',
    ],
    'vale_do_caninde': [
        'Bela Vista do Pi',
        'Cajazeiras do Pi',
        'Campinas do Pi',
        'Colonia do Pi',
        'Conceicao do Caninde',
        'Floresta do Pi',
        'Isaias Coelho',
        'Oeiras',
        'Santa Cruz do Pi',
        'Santa Rosa do Pi',
        'Santo Inacio do Pi',
        'Sao Francisco de Assis do Pi',
        'Sao Francisco do Pi',
        'Sao Joao da Varjota',
        'Simplicio Mendes',
        'Tanque do Pi',
        'Wall Ferraz',
    ],
    'serra_da_capivara': [
        'Anisio de Abreu',
        'Bonfim do Pi',
        'Campo Alegre do Fidalgo',
        'Capitao Gervasio Oliveira',
        'Caracol',
        'Coronel Jose Dias',
        'Dirceu Arcoverde',
        'Dom Inocencio',
        'Fartura do Pi',
        'Guaribas',
        'Joao Costa',
        'Jurema',
        'Lagoa do Barro do Pi',
        'Sao Braz do Pi',
        'Sao Joao do Pi',
        'Sao Lourenco do Pi',
        'Sao Raimundo Nonato',
        'Varzea Branca',
    ],
    'mangabeiras': [
        'Alvorada do Gurgueia',
        'Avelino Lopes',
        'Barreiras do Pi',
        'Bom Jesus',
        'Colonia do Gurgueia',
        'Corrente',
        'Cristalandia do Pi',
        'Cristino Castro',
        'Currais',
        'Curimata',
        'Eliseu Martins',
        'Gilbues',
        'Julio Borges',
        'Manoel Emidio',
        'Monte Alegre do Pi',
        'Morro Cabeca no Tempo',
        'Palmeira do Pi',
        'Parnagua',
        'Redencao do Gurgueia',
        'Riacho Frio',
        'Santa Filomena',
        'Santa Luz',
        'Sao Goncalo do Gurgueia',
        'Sebastiao Barros',
    ],
}
